### ISSUE TITLE
[FEATURE] External PostgreSQL Support

### ISSUE THREAD

**Issue by drag0n141** [l4rm4nd/VoucherVault#20]
Hey,

it would be nice to add support for external databases like postgresql. It would me much easier to host it in a kubernetes cluster and scale the pod.

**Comment by l4rm4nd** [comment]
Currently being implemented in the feature branch:

https://github.com/l4rm4nd/VoucherVault/tree/feature-psql

Seems to work already but needs more testing for stable release.

You may build the Docker image locally and try it out.

````
# build the feature branch image
docker build -t vouchervault-psql -f docker/Dockerfile .
````

Then use the adjusted docker-compose.yml with the new PSQL container and environment variables:

````
services:

  vouchervault:
    image: l4rm4nd/vouchervault:1.1.x # pin a minor version series tag instead of latest
    container_name: vouchervault
    environment:
      - DOMAIN=vouchervault.example.com # your FQDN or IP; used to define ALLOWED_HOSTS and CSRF_TRUSTED_ORIGINS
      - SECURE_COOKIES=False # set to True if you use a reverse proxy with tls; enables secure cookie flag and hsts
      - EXPIRY_THRESHOLD_DAYS=90 # send notifications xx days prior expiry; default is 30
      # ------- PSQL DB ENVS --------
      - DB_ENGINE=postgres
      - POSTGRES_USER=vouchervault
      - POSTGRES_PASSWORD=vouchervault
      - POSTGRES_DB=vouchervault
      - POSTGRES_HOST=vouchervault-psql
      - POSTGRES_PORT=5432
    restart: unless-stopped
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./volume-data/database:/opt/app/database

  redis:
    container_name: vouchervault-redis
    image: redis:7.2-alpine
    restart: unless-stopped
    expose:
      - 6379

  db:
    container_name: vouchervault-psql
    image: postgres:16-alpine
    restart: unless-stopped
    expose:
      - 5432
    volumes:
      - ./volume-data/database/psql:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=vouchervault
      - POSTGRES_PASSWORD=vouchervault
      - POSTGRES_DB=vouchervault
````
