### ISSUE TITLE
[BUG]  www-data user issue / container not starting

### ISSUE THREAD

**Issue by moostmartijn** [l4rm4nd/VoucherVault#36]
**Describe the bug**
I had Vouchervault running, but after upgrading to the latest version it stopped working. So I checked the Github page and found that it needs permissions for the www-data user. 

Unfortunately the container won't start because the bind volume does not have the right permissions. But... This sudo chown is not working:
myuser@NAS:/volume3/apps/vouchervault$ sudo chown -R www-data:www-data vouchervault/*
chown: invalid user: ‘www-data:www-data’

I'm just not sure what to do in this situation so I hope you can help me with this. Thanks in advance.

This is my docker-compose:
```
services:
  vouchervault:
    image: l4rm4nd/vouchervault:latest # pin a minor version series tag instead of latest
    container_name: vouchervault
    environment:
      - DOMAIN=192.168.1.11 # your FQDN or IP; used to define ALLOWED_HOSTS and CSRF_TRUSTED_ORIGINS
      - SECURE_COOKIES=False # set to True if you use a reverse proxy with tls; enables secure cookie flag and hsts
      - EXPIRY_THRESHOLD_DAYS=60 # send notifications xx days prior expiry; default is 30
    restart: unless-stopped
    expose:
      - 8000
    ports:
      - 8010:8000
    volumes:
      - /volume3/apps/vouchervault/database:/opt/app/database

  redis:
    container_name: vouchervault-redis
    image: redis:7.2-alpine
    restart: unless-stopped  
```
